# --- Main Colors ---
background            #0f1417
foreground            #dfe3e7
cursor                #dfe3e7
cursor_text_color     #0f1417

selection_background  #364954
selection_foreground  #d1e5f3

url_color             #c9c1ea

# --- ANSI Colors ---
color0                #0f1417
color1                #ffb4ab
color2                #c9c1ea
color3                #b5c9d7
color4                #8ecff2
color5                #c9c1ea
color6                #b5c9d7
color7                #dfe3e7

color8                #40484d
color9                #93000a
color10               #484264
color11               #364954
color12               #004d68
color13               #364954
color14               #484264
color15               #c0c7cd

# --- Starship Prompt Bubbles ---
color255              #004d68
color254              #8ecff2
color253              #364954
color252              #b5c9d7
color251              #484264
color250              #c9c1ea
color249              #93000a
color248              #ffb4ab

color232              #c2e8ff
color233              #003549
color234              #d1e5f3
color235              #20333d
color236              #e5deff
color237              #312c4c
color238              #ffdad6
color239              #690005
color240              #c2e8ff

# Matched with unthemed light/dark
color243              #8ecff2
color244              #ffb4ab
color245              #40484d

# --- UI Elements ---
active_tab_foreground   #003549
active_tab_background   #8ecff2
inactive_tab_foreground #c2e8ff
inactive_tab_background #004d68

active_border_color     #8ecff2
inactive_border_color   #8a9297

# --- Marks ---
mark1_foreground        #001e2c
mark1_background        #c2e8ff
mark2_foreground        #091e28
mark2_background        #d1e5f3
mark3_foreground        #1c1736
mark3_background        #e5deff