cursor            #99ccf9
cursor_text_color #003351

foreground            #e0e2e8
background            #0b0f12
selection_foreground  #23323f
selection_background  #b8c8da
url_color             #b8c8da

#: black 000000 767676
color0  #101418
color8  #313539
#: red cc0403 f2201f
color1  #667384
color9  #667384
#: green 19cb00 23fd00
color2  #b8c8da
color10 #d4e4f6
#: yellow cecb00 fffd00
color3  #d1bfe7
color11 #eddcff
#: blue 0d73cc 1a8fff
color4  #064b72
color12 #99ccf9
#: magenta cb1ed1 fd28ff
color5  #394857
color13 #b8c8da
#: cyan 0dcdcd 14ffff
color6  #4e4162
color14 #d1bfe7
#: white dddddd ffffff
color7  #c2c7ce
color15 #e0e2e8

mark1_foreground #001d31
mark1_background #cce5ff
mark2_foreground #0d1d2a
mark2_background #d4e4f6
mark3_foreground #221534
mark3_background #eddcff

active_tab_foreground #003351
active_tab_background #99ccf9
inactive_tab_foreground #cce5ff
inactive_tab_background #064b72

active_border_color #99ccf9
inactive_border_color #003351