cursor            #cdbdff
cursor_text_color #34275e

foreground            #e6e1e9
background            #0f0d13
selection_foreground  #322e41
selection_background  #cbc3dc
url_color             #cbc3dc

#: black 000000 767676
color0  #141318
color8  #36343a
#: red cc0403 f2201f
color1  #3b3452
color9  #3b3452
#: green 19cb00 23fd00
color2  #cbc3dc
color10 #e7def8
#: yellow cecb00 fffd00
color3  #efb8c9
color11 #ffd9e4
#: blue 0d73cc 1a8fff
color4  #4b3e76
color12 #cdbdff
#: magenta cb1ed1 fd28ff
color5  #494458
color13 #cbc3dc
#: cyan 0dcdcd 14ffff
color6  #633b49
color14 #efb8c9
#: white dddddd ffffff
color7  #cac4cf
color15 #e6e1e9

mark1_foreground #1f1048
mark1_background #e8ddff
mark2_foreground #1d192b
mark2_background #e7def8
mark3_foreground #31111e
mark3_background #ffd9e4

active_tab_foreground #34275e
active_tab_background #cdbdff
inactive_tab_foreground #e8ddff
inactive_tab_background #4b3e76

active_border_color #cdbdff
inactive_border_color #34275e