colors = require("colors")
require("modules.env")
require("modules.permissions")
require("modules.monitors")
require("modules.autostart")
require("modules.appearance")
require("modules.animations")
require("modules.input")
require("modules.workspaces")
require("modules.windowrules")
require("modules.binds")